### ISSUE TITLE
Team onboarding: git

### ISSUE THREAD

**Issue by britthurley** [dtf-ein/reading-material#3]
We need to develop a clear team onboarding process for the DTF, as people with varying technical abilities will be joining the team.

The first item in that set of materials should be using GitHub. We need a clear read me on how to do the following:
- Download and install Git
- A way to use git from your desktop (we need to determine a base method for those that don't have a preffered - Visual Studio Code?)
- commit procedures, etc.

Doc can be linked to other sources, of course.

Jessica can be the tester for the initial version.

**Comment by patheard** [comment]
As part of this, I'm going to create a project where new users can practice the [GitHub flow](https://guides.github.com/introduction/flow/).  It'll be a similar idea to the [cds-snc/etait-ici](https://github.com/cds-snc/etait-ici) project.

**Comment by patheard** [comment]
H'ok, I created the [hello](https://github.com/SSC-CIO-DigitalTaskForce/hello) example project, with a guide on how to work in the command line.  Let me know what you think!

We could also buff this up to include guides for VS Code or other Git clients so people don't have to use the command line.

**Comment by patheard** [comment]
Alrighty, rewrote the instructions for GitHub Desktop.  Way more user friendly process:

https://github.com/SSC-CIO-DigitalTaskForce/hello/blob/master/README.md

Once we start onboarding people, we can tweak where it's not working or unclear!

**Comment by patheard** [comment]
@jessmardo and I went through the setup and so far so good.

I'm going to rework the hello project README to use VS Code when I've got a chance since it's an awkward workflow to go back and forth between GitHub Desktop and a file editor.
